// Program import — parses the openGym Excel/CSV template into Zustand routines.
//
// Supports two input formats:
//   Excel (.xlsx) — generated by excelTemplate.js; uses SheetJS to convert to rows
//   CSV           — legacy format with comma-separated values
//
// Column layout (new template):
//   A: Programme | B: Séance | C: N° Séance | D: N° Exercice |
//   E: Groupe Musculaire | F: Exercice | G: Tempo | H: Séries | I: Répétitions | J: Poids (kg) | K: Repos (sec)
//
// Superset detection via N° Exercice column:
//   "1", "2", "3" → normal exercises
//   "2A", "2B"    → superset (same numeric prefix → linked with shared sg id)
//   "3A", "3B", "3C" → tri-set

import { EXDB } from './exercises.js'
import { uid } from './format.js'

// ──────────────────────────────────────────────────────────────────────────
// Fuzzy exercise name matching
// ──────────────────────────────────────────────────────────────────────────

const norm = s => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
const STOP = new Set(['barbell','dumbbell','machine','cable','with','and','the','using'])

function wordScore(query, candidate) {
  const qw = norm(query).split(' ').filter(w => w.length > 1 && !STOP.has(w))
  const cw = norm(candidate).split(' ').filter(w => w.length > 1 && !STOP.has(w))
  if (!qw.length) return 0
  const hits = qw.filter(w => cw.includes(w)).length
  return hits / Math.max(qw.length, cw.length)
}

export function findExercise(name, exercises = EXDB) {
  if (!name?.trim()) return null
  const target = norm(name)
  const exact  = exercises.find(e => norm(e.n) === target)
  if (exact) return exact
  const sub = exercises.find(e => { const c = norm(e.n); return c.includes(target) || target.includes(c) })
  if (sub) return sub
  let best = null, bestScore = 0
  for (const ex of exercises) {
    const s = wordScore(target, ex.n)
    if (s > bestScore) { bestScore = s; best = ex }
  }
  return bestScore >= 0.5 ? best : null
}

// ──────────────────────────────────────────────────────────────────────────
// Exercise number parsing (for superset detection)
// ──────────────────────────────────────────────────────────────────────────
// "1"  → { num: 1, suffix: '' }   normal exercise
// "2A" → { num: 2, suffix: 'A' }  first exercise of superset #2
// "2B" → { num: 2, suffix: 'B' }  second exercise of superset #2

function parseExNum(raw) {
  const s  = String(raw || '').trim()
  const m  = s.match(/^(\d+)([A-Za-z]?)$/)
  if (!m) return { num: parseInt(s, 10) || 0, suffix: '' }
  return { num: parseInt(m[1], 10), suffix: m[2].toUpperCase() }
}

// ──────────────────────────────────────────────────────────────────────────
// Row parser (shared between CSV and Excel paths)
// ──────────────────────────────────────────────────────────────────────────

function normSport(s) {
  const m = {
    run: 'run', course: 'run', running: 'run', jogging: 'run',
    walk: 'walk', marche: 'walk', walking: 'walk',
    bike: 'bike', velo: 'bike', cycling: 'bike', cycle: 'bike',
    swim: 'swim', natation: 'swim', swimming: 'swim',
    aqua: 'aqua', aquagym: 'aqua', aquabike: 'aqua',
  }
  return m[s] || s || 'run'
}

function parseRows(rows, exercises = EXDB) {
  // Strip accents, lowercase, collapse non-alphanumeric runs to one space.
  // This makes "N° Exercice" → "n exercice" and "Exercice" → "exercice",
  // which is required so colOf can distinguish the two via exact match.
  const normH = s => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()

  // Auto-detect column layout from the header row
  const headerRow = rows.find(r => {
    const h = r.map(c => normH(c))
    return h.some(c => c === 'programme' || c === 'seance' || c.includes('program') || c.includes('session'))
  })

  let progCol = 0, sessionCol = 1, sesNumCol = 2, exNumCol = 3, bpCol = 4, exCol = 5
  let tempoCol = 6, setsCol = 7, repsCol = 8, weightCol = 9, restCol = 10
  let cardioTypeCol = -1, cardioSportCol = -1, cardioDurCol = -1, cardioDistCol = -1
  let cardioIntCol = -1, cardioRepCol = -1, cardioWorkCol = -1, cardioRestCol = -1
  let imageUrlCol = -1

  let programName = 'Imported program'
  let programImageUrl = null
  let dataStartRow = 0

  if (headerRow) {
    const h = headerRow.map(c => normH(c))
    const colOf = (...keywords) => {
      const norms = keywords.map(normH)
      // Exact match first — prevents "n exercice" from matching keyword "exercice"
      const exact = h.findIndex(c => norms.includes(c))
      if (exact >= 0) return exact
      // Partial match fallback (handles compound headers like "groupe musculaire" → "groupe")
      return h.findIndex(c => norms.some(k => c.includes(k) || k.includes(c)))
    }

    progCol    = colOf('programme', 'program')
    sessionCol = colOf('séance', 'seance', 'session')
    sesNumCol  = colOf('n° séance', 'n seance', 'session num')
    exNumCol   = colOf('n° exercice', 'n exercice', 'exercise num', 'ex num')
    bpCol      = colOf('groupe musculaire', 'groupe', 'muscle group', 'body part', 'bp')
    exCol      = colOf('exercice', 'exercise')
    tempoCol   = colOf('tempo')
    setsCol    = colOf('séries', 'series', 'sets')
    repsCol    = colOf('répétitions', 'repetitions', 'reps')
    weightCol  = colOf('poids', 'weight')
    restCol      = colOf('repos', 'rest')
    cardioTypeCol  = colOf('type cardio', 'cardio type', 'type bloc')
    cardioSportCol = colOf('sport cardio', 'sport')
    cardioDurCol   = colOf('duree min', 'duree', 'duration')
    cardioDistCol  = colOf('distance km', 'distance')
    cardioIntCol   = colOf('intensite 1 5', 'intensite', 'intensity')
    cardioRepCol   = colOf('intervalles')
    cardioWorkCol  = colOf('travail s', 'travail')
    cardioRestCol  = colOf('recup s', 'recup', 'recuperation s')
    imageUrlCol    = colOf('image url', 'image programme', 'image', 'cover')

    // Fall back to positional if detection fails
    if (progCol    < 0) progCol    = 0
    if (sessionCol < 0) sessionCol = 1
    if (sesNumCol  < 0) sesNumCol  = 2
    if (exNumCol   < 0) exNumCol   = 3
    if (bpCol      < 0) bpCol      = 4
    if (exCol      < 0) exCol      = 5
    if (tempoCol   < 0) tempoCol   = 6
    if (setsCol    < 0) setsCol    = 7
    if (repsCol    < 0) repsCol    = 8
    if (weightCol  < 0) weightCol  = 9
    if (restCol    < 0) restCol    = 10

    dataStartRow = rows.indexOf(headerRow) + 1
  }

  const warnings   = []
  const workoutMap = new Map()   // sessionName → [exerciseConfig]
  const workoutOrder = []        // preserves insertion order for session numbering

  for (let i = dataStartRow; i < rows.length; i++) {
    const cells = rows[i]
    if (!cells || cells.every(c => !c)) continue  // blank row

    const program  = String(cells[progCol]    || '').trim()
    const session  = String(cells[sessionCol] || '').trim()
    const exNumRaw = cells[exNumCol]
    const bpRaw    = String(cells[bpCol]      || '').trim()
    const exName   = String(cells[exCol]      || '').trim()
    const tempo    = String(cells[tempoCol]   || '').trim()
    const sets     = parseInt(cells[setsCol],  10) || 3
    const reps     = parseInt(cells[repsCol],  10) || 10
    const rest     = parseInt(cells[restCol],  10) || 90

    const cardioType = cardioTypeCol >= 0 ? String(cells[cardioTypeCol] || '').trim().toLowerCase() : ''

    if (!session) continue
    if (!exName && !cardioType) continue
    if (i === dataStartRow && !program && !cardioType) continue  // skip if looks like a header

    if (program && !programName.includes('Imported')) programName = program
    if (!programImageUrl && imageUrlCol >= 0) {
      const v = String(cells[imageUrlCol] || '').trim()
      if (v) programImageUrl = v
    }

    if (!workoutMap.has(session)) {
      workoutMap.set(session, [])
      workoutOrder.push(session)
    }

    if (cardioType) {
      const sport     = normSport(cardioSportCol >= 0 ? String(cells[cardioSportCol] || '').trim().toLowerCase() : 'run')
      const duration  = cardioDurCol  >= 0 ? (parseInt(cells[cardioDurCol],  10) || 10) : 10
      const distKm    = cardioDistCol >= 0 ? (parseFloat(cells[cardioDistCol]) || null) : null
      const rawInt    = cardioIntCol  >= 0 ? String(cells[cardioIntCol] || '').trim() : '3'
      const intensity = parseInt(rawInt, 10) || 3
      let blockData
      if (cardioType === 'interval') {
        const repeat  = cardioRepCol  >= 0 ? (parseInt(cells[cardioRepCol],  10) || 6)  : 6
        const workSec = cardioWorkCol >= 0 ? (parseInt(cells[cardioWorkCol], 10) || 60) : 60
        const restSec = cardioRestCol >= 0 ? (parseInt(cells[cardioRestCol], 10) || 90) : 90
        blockData = { kind: 'block', sport, type: 'interval', repeat, workSec, restSec, workIntensity: intensity, restIntensity: Math.max(1, intensity - 2) }
      } else {
        blockData = { kind: 'block', sport, type: cardioType, duration, intensity }
        if (distKm) blockData.distKm = distKm
      }
      workoutMap.get(session).push(blockData)
      continue
    }

    const { num: exNum, suffix } = parseExNum(exNumRaw)
    const matched = findExercise(exName, exercises)

    if (!matched) {
      warnings.push(`Exercise not found: "${exName}" (session "${session}") — skipped`)
      continue
    }

    const entry = {
      id: matched.id,
      sets,
      reps,
      weight: 0,
      mode: 'reps',
    }

    if (tempo) entry.tempo = tempo
    if (rest)  entry.restSec = rest

    // Superset: exercises sharing the same num with a letter suffix are grouped
    if (suffix) {
      // sgKey is scoped per session to avoid cross-session grouping
      entry._sgKey = `${session}:${exNum}`
    }

    workoutMap.get(session).push(entry)
  }

  if (!programName || programName === 'Imported program') {
    // Try to get the name from the first data row
    const firstRow = rows[dataStartRow]
    if (firstRow?.[progCol]) programName = String(firstRow[progCol]).trim()
  }

  // Resolve superset sg ids
  const sgIds = new Map()
  const getSg  = key => { if (!sgIds.has(key)) sgIds.set(key, 'sg' + uid()); return sgIds.get(key) }

  const routines = workoutOrder.map(sessionName => {
    const entries = workoutMap.get(sessionName)
    const hasBlocks = entries.some(e => e.kind === 'block')

    if (hasBlocks) {
      const items = entries.map(e => {
        if (e.kind === 'block') return { ...e, id: uid() }
        const { _sgKey, ...rest } = e
        if (_sgKey) rest.sg = getSg(_sgKey)
        return { kind: 'ex', ...rest }
      })
      return { id: uid(), name: sessionName, emoji: null, items, prog: 'linear' }
    }

    const ex = entries.map(e => {
      const { _sgKey, ...rest } = e
      if (_sgKey) rest.sg = getSg(_sgKey)
      return rest
    })
    return { id: uid(), name: sessionName, emoji: null, ex, prog: 'linear' }
  })

  return { programName: programName || 'Imported program', routines, warnings, programImageUrl }
}

// ──────────────────────────────────────────────────────────────────────────
// CSV parser (preserves backward compatibility)
// ──────────────────────────────────────────────────────────────────────────

function parseCSVLine(line) {
  const cells = []; let cur = '', inQ = false
  for (const ch of line) {
    if (ch === '"') { inQ = !inQ }
    else if (ch === ',' && !inQ) { cells.push(cur.trim()); cur = '' }
    else { cur += ch }
  }
  cells.push(cur.trim())
  return cells
}

export function parseProgramCSV(csvText, exercises = EXDB) {
  const lines = csvText.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n')

  let programName = 'Imported program'
  const dataRows  = []

  for (const rawLine of lines) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const cells = parseCSVLine(line)
    // "Program,My Name" header shorthand (legacy format)
    if (cells[0].toLowerCase() === 'program' && cells.length === 2) {
      programName = cells[1] || programName
      continue
    }
    dataRows.push(cells)
  }

  if (!dataRows.length) {
    return { programName, routines: [], warnings: ['No data found in file.'] }
  }

  const result = parseRows(dataRows, exercises)
  if (programName !== 'Imported program' && result.programName === 'Imported program') {
    result.programName = programName
  }
  return result
}

// ──────────────────────────────────────────────────────────────────────────
// Excel (.xlsx) parser — uses SheetJS (dynamically imported)
// ──────────────────────────────────────────────────────────────────────────

export async function parseProgramXLSX(arrayBuffer, exercises = EXDB) {
  const XLSX    = await import('xlsx')
  const wb      = XLSX.read(arrayBuffer, { type: 'array' })

  // Use the first non-hidden sheet that is not "Lists" or "Instructions"
  const sheetName = wb.SheetNames.find(
    n => !['lists', 'instructions'].includes(n.toLowerCase())
  ) || wb.SheetNames[0]

  const ws   = wb.Sheets[sheetName]
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' })

  // Extract program name from top-left if it's a metadata cell
  let programName = 'Imported program'
  if (rows[0]?.[0] && String(rows[0][0]).toLowerCase().includes('programme')) {
    // skip — it's the column header
  }

  const result = parseRows(rows, exercises)
  if (result.programName === 'Imported program') result.programName = programName
  return result
}

// ──────────────────────────────────────────────────────────────────────────
// Unified entry point — detects format from file extension / MIME type
// ──────────────────────────────────────────────────────────────────────────

export async function parseProgram(file) {
  const name  = (file.name || '').toLowerCase()
  const isXLS = name.endsWith('.xlsx') || name.endsWith('.xls') || name.endsWith('.xlsm')
    || file.type?.includes('spreadsheet') || file.type?.includes('excel')

  if (isXLS) {
    const buf = await file.arrayBuffer()
    return parseProgramXLSX(buf)
  }

  const text = await file.text()
  return parseProgramCSV(text)
}
